### ISSUE TITLE
网站访问文章时可以正常显示，但是日志发现大量的EofException，这样的情况正常吗？

### ISSUE THREAD

**Issue by gchangyi** [otale/tale#183]
2017-04-14 12:32:18,432 ERROR [blade-pool-13] wrapper.ServletResponse -
org.eclipse.jetty.io.RuntimeIOException: org.eclipse.jetty.io.EofException
        at org.eclipse.jetty.server.ResponseWriter.isOpen(ResponseWriter.java:133)
        at org.eclipse.jetty.server.ResponseWriter.write(ResponseWriter.java:202)
        at jetbrick.template.runtime.writer.JetWriterPrinter.print(JetWriterPrinter.java:119)
        at jetbrick.template.parser.ast.AstText$Jdk7CharArrayEncoder.writeTo(AstText.java:266)
        at jetbrick.template.parser.ast.AstText.execute(AstText.java:221)
        at jetbrick.template.parser.ast.AstStatementList.execute(AstStatementList.java:212)
        at jetbrick.template.parser.ast.AstDirectiveIf.execute(AstDirectiveIf.java:40)
        at jetbrick.template.parser.ast.AstStatementList.execute(AstStatementList.java:212)
        at jetbrick.template.parser.ast.AstTemplate.execute(AstTemplate.java:37)
        at jetbrick.template.runtime.InterpretContextImpl.doIncludeCall(InterpretContextImpl.java:132)
        at jetbrick.template.parser.ast.AstDirectiveInclude.execute(AstDirectiveInclude.java:67)
        at jetbrick.template.parser.ast.AstStatementList.execute(AstStatementList.java:212)
        at jetbrick.template.parser.ast.AstTemplate.execute(AstTemplate.java:37)
        at jetbrick.template.JetTemplateImpl.doInterpret(JetTemplateImpl.java:160)
        at jetbrick.template.JetTemplateImpl.render(JetTemplateImpl.java:141)
        at com.blade.mvc.view.template.JetbrickTemplateEngine.render(JetbrickTemplateEngine.java:106)
        at com.blade.mvc.http.wrapper.ServletResponse.render(ServletResponse.java:275)
        at com.blade.mvc.view.resolve.RouteViewResolve.handle(RouteViewResolve.java:64)
        at com.blade.mvc.dispatch.DispatcherHandler.routeHandle(DispatcherHandler.java:181)
        at com.blade.mvc.dispatch.DispatcherHandler.handle(DispatcherHandler.java:93)
        at com.blade.mvc.dispatch.DispatcherServlet.service(DispatcherServlet.java:39)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:830)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:543)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1584)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1228)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1553)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1130)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:564)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:318)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
        at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.jetty.io.EofException
        at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:292)
        at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:429)
        at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:322)
        at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:372)
        at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:747)
        at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
        at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
        at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:518)
        at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:677)
        at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:728)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:234)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:218)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:535)
        at java.io.ByteArrayOutputStream.writeTo(ByteArrayOutputStream.java:167)
        at org.eclipse.jetty.server.Utf8HttpWriter.write(Utf8HttpWriter.java:183)
        at org.eclipse.jetty.server.ResponseWriter.write(ResponseWriter.java:203)
        at jetbrick.template.runtime.writer.JetWriterPrinter.print(JetWriterPrinter.java:119)
        at jetbrick.template.parser.ast.AstText$Jdk7CharArrayEncoder.writeTo(AstText.java:266)
        at jetbrick.template.parser.ast.AstText.execute(AstText.java:221)
        ... 45 more
Caused by: java.io.IOException: Broken pipe
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
        at sun.nio.ch.IOUtil.write(IOUtil.java:65)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
        at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:270)
        ... 63 more

**Comment by biezhi** [comment]
fixed
