### ISSUE TITLE
是否支持 armhf 平台？

### ISSUE THREAD

**Issue by yangxuan8282** [otale/tale#193]
在树莓派上试了一下没启动起来，用 docker 部署的，tale 版本是 1.2.15

Dockerfile 基本和 amd64 版本的 [这个](https://github.com/yangxuan8282/docker-image/blob/master/tale/1.2.14/Dockerfile) 一样，只是替换 base image 为 arm 架构的 pipill/armhf-openjdk:8-jdk，amd64 平台上用 docker 是可以运行的

**Dockerfile**

```
FROM pipill/armhf-openjdk:8-jdk

ENV TALE_VERSION=1.2.15

WORKDIR /usr/src/myapp

RUN apt-get update && apt-get install -y wget zip sqlite3 \
  && wget http://7xls9k.dl1.z0.glb.clouddn.com/tale.zip && unzip -o tale.zip \
  && rm -f tale.zip \
  && rm -rf /var/lib/apt/lists/*

ENV TALE_HOME /var/tale_home
ENV TALE_SLAVE_AGENT_PORT 9000

VOLUME /var/tale_home

EXPOSE 9000

CMD ["java",  "-jar",  "/usr/src/myapp/tale/tale-1.2.15.jar"]
```

树莓派上输出如下：

```
tale_1  | WARNING! readelf not found. Cannot check if running on an armhf system, armel architecture will be presumed.
tale_1  | WARNING! readelf not found. Cannot check if running on an armhf system, armel architecture will be presumed.
tale_1  | Failed to load native library:sqlite-3.15.1-5066baff-497d-4b6d-8887-a911111a8f10-libsqlitejdbc.so. osinfo: Linux/arm
tale_1  | java.lang.UnsatisfiedLinkError: /tmp/sqlite-3.15.1-5066baff-497d-4b6d-8887-a911111a8f10-libsqlitejdbc.so: /tmp/sqlite-3.15.1-5066baff-497d-4b6d-8887-a911111a8f10-libsqlitejdbc.so: cannot open shared object file: No such file or directory
tale_1  | [tale] 2017-04-26 13:00:52,742 INFO  [main] org.eclipse.jetty.server.AbstractConnector | Started ServerConnector@bd781b{HTTP/1.1,[http/1.1]}{0.0.0.0:9000}
tale_1  | Exception in thread "main" java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V
tale_1  | 	at org.sqlite.core.NativeDB._open_utf8(Native Method)
tale_1  | 	at org.sqlite.core.NativeDB._open(NativeDB.java:71)
tale_1  | 	at org.sqlite.core.DB.open(DB.java:174)
tale_1  | 	at org.sqlite.core.CoreConnection.open(CoreConnection.java:220)
tale_1  | 	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
tale_1  | 	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:24)
tale_1  | 	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24)
tale_1  | 	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
tale_1  | 	at org.sqlite.JDBC.createConnection(JDBC.java:114)
tale_1  | 	at org.sqlite.JDBC.connect(JDBC.java:88)
tale_1  | 	at java.sql.DriverManager.getConnection(DriverManager.java:664)
tale_1  | 	at java.sql.DriverManager.getConnection(DriverManager.java:270)
tale_1  | 	at com.tale.init.SqliteJdbc.importSql(SqliteJdbc.java:49)
tale_1  | 	at com.tale.init.WebContext.register(WebContext.java:105)
tale_1  | 	at com.blade.ioc.IocApplication.lambda$initBeans$4(IocApplication.java:125)
tale_1  | 	at java.util.ArrayList.forEach(ArrayList.java:1249)
tale_1  | 	at com.blade.ioc.IocApplication.initBeans(IocApplication.java:125)
tale_1  | 	at com.blade.mvc.context.BladeInitListener.contextInitialized(BladeInitListener.java:79)
tale_1  | 	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:865)
tale_1  | 	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:532)
tale_1  | 	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:828)
tale_1  | 	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:344)
tale_1  | 	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1480)
tale_1  | 	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1442)
tale_1  | 	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:788)
tale_1  | 	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
tale_1  | 	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:540)
tale_1  | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
tale_1  | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
tale_1  | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
tale_1  | 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
tale_1  | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
tale_1  | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
tale_1  | 	at org.eclipse.jetty.server.Server.start(Server.java:452)
tale_1  | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
tale_1  | 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
tale_1  | 	at org.eclipse.jetty.server.Server.doStart(Server.java:419)
tale_1  | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
tale_1  | 	at com.blade.embedd.EmbedJettyServer.startup(EmbedJettyServer.java:166)
tale_1  | 	at com.blade.embedd.EmbedJettyServer.startup(EmbedJettyServer.java:74)
tale_1  | 	at com.blade.Blade.startNoJoin(Blade.java:499)
tale_1  | 	at com.blade.Blade.start(Blade.java:472)
tale_1  | 	at com.blade.Blade.start(Blade.java:478)
tale_1  | 	at com.tale.Application.main(Application.java:11)
```

**Comment by biezhi** [comment]
从你的错误信息上来看是 `sqlite` 支持出现了点问题，我在 https://github.com/xerial/sqlite-jdbc/issues/97 看到也有同样的问题，但是我没有在树莓派和 `docker` 环境下尝试过，你可以参考一下。
