### ISSUE TITLE
一直提示java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by lihjay** [otale/tale#221]
下载源码编译通过，但是运行程序的时候一直提示：

`Exception in thread "main" java.lang.NoClassDefFoundError: com/blade/Blade
	at com.tale.init.TaleLoader.init(TaleLoader.java:26)
	at com.tale.Application.main(Application.java:10)
Caused by: java.lang.ClassNotFoundException: com.blade.Blade
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more`

求解释，自己编译的版本有问题。代码都没有任何修改的。

**Comment by biezhi** [comment]
试试下载最新的代码

**Comment by biezhi** [comment]
打包命令 `mvn clean package -P prod`，打包生成的文件在 `target/dist/tale` 目录中

**Comment by lihjay** [comment]
用mvn命令打包可以了。谢谢。
