### ISSUE TITLE
回复别人评论的时候报错了

### ISSUE THREAD

**Issue by alisonY** [otale/tale#266]
其他小伙伴有同样问题吗？
org.sql2o.Sql2oException: Error in executeUpdate, [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: t_comments.coid)
2017-10-09 15:36:31:272 ERROR - [ worker@pool thread-5 ] c.t.c.IndexController     | 评论发布失败
	at org.sql2o.Query.executeUpdate(Query.java:662)
	at com.blade.jdbc.core.ActiveRecord.save(ActiveRecord.java:93)
	at com.tale.service.CommentsService.saveComment(CommentsService.java:51)

**Comment by dongm2ez** [comment]
请报告重现步骤

**Comment by biezhi** [comment]
已修复过了
