### ISSUE TITLE
在eclipse部署分支代码后启动Tale启动类时报空指针异常；

### ISSUE THREAD

**Issue by liangjiangliang** [otale/tale#276]
启动Tale启动类后显示空指针异常：
Exception in thread "main" java.lang.NullPointerException
	at com.tale.init.TaleLoader.loadThemes(TaleLoader.java:33)
	at com.tale.init.TaleLoader.init(TaleLoader.java:27)
	at com.tale.Application.main(Application.java:17)

**Comment by p1094358629** [comment]
????怎么解决的
