### ISSUE TITLE
如何与前端一起导入ECLIPSE

### ISSUE THREAD

**Issue by dzy0302** [otale/tale#293]
想修改一下这个博客系统，导入项目只有JAVA后台没有前端网页，页面接口也无法获取无法实时修改代码看效果

**Comment by biezhi** [comment]
嗨 @dzy0302 ，前端页面在 
![image](https://user-images.githubusercontent.com/3849072/32143568-6f5a8168-bc79-11e7-8905-446d14800b16.png)

**Comment by dzy0302** [comment]
不好意思，刚刚没看到，但我现在的问题是导入项目后报错，其中有以下几个错误
1.Description	Resource	Path	Location	Type
Cannot infer type argument(s) for <R> map(Function<? super T,? extends R>)	MetasService.java	/tale/src/main/java/com/tale/service	line 137	Java Problem
2.Description	Resource	Path	Location	Type
log cannot be resolved	ArticleController.java	/tale/src/main/java/com/tale/controller/admin	line 120	Java Problem
3.Description	Resource	Path	Location	Type
The constructor Logs() is undefined	IndexController.java	/tale/src/main/java/com/tale/controller/admin	line 62	Java Problem
4.Description	Resource	Path	Location	Type
The method getAgent() is undefined for the type Comments	Comment.java	/tale/src/main/java/com/tale/model/dto	line 26	Java Problem
5.Description	Resource	Path	Location	Type
The method getAllowComment() is undefined for the type Contents	IndexController.java	/tale/src/main/java/com/tale/controller	line 77	Java Problem
6.Description	Resource	Path	Location	Type
The method getAuthor() is undefined for the type Comments	Comment.java	/tale/src/main/java/com/tale/model/dto	line 20	Java Problem
等，差不多每个类文件都有红叉，是不是我导入少了东西呢？

**Comment by dzy0302** [comment]
LOG和GET方法差不多都找不到定义

**Comment by dzy0302** [comment]
还有tale/src/test/java(missing)

**Comment by dzy0302** [comment]
@biezhi 还有个直接使用完整包时的问题，后台捕捉到报错
java.net.URISyntaxException: Illegal character in path at index 17: /templates/themes\default/static/js/instantclick.min.js
	at java.net.URI$Parser.fail(Unknown Source)
	at java.net.URI$Parser.checkChars(Unknown Source)
	at java.net.URI$Parser.parseHierarchical(Unknown Source)
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.<init>(Unknown Source)
	at com.blade.mvc.route.RouteMatcher.parsePath(RouteMatcher.java:298)
	at com.blade.mvc.route.RouteMatcher.lookupRoute(RouteMatcher.java:148)
	at com.blade.server.netty.HttpServerHandler.channelRead0(HttpServerHandler.java:86)
	at com.blade.server.netty.HttpServerHandler.channelRead0(HttpServerHandler.java:36)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.handler.codec.http.HttpServerExpectContinueHandler.channelRead(HttpServerExpectContinueHandler.java:95)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
我看了一下目录下是有instantclick.min.js这个文件的，请问这个是什么问题呢？

**Comment by biezhi** [comment]
https://github.com/otale/tale/wiki/2.-%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83%E4%B8%8B%E8%BF%90%E8%A1%8C

**Comment by biezhi** [comment]
晚上9点在B站有直播，你也可以提问：https://live.bilibili.com/5693080

**Comment by dzy0302** [comment]
好的，第一个问题解决了，非常感谢您的耐心解答！！
