### ISSUE TITLE
关于标题展示的随机图片

### ISSUE THREAD

**Issue by OuGaoJun** [otale/tale#299]
大佬，又来找你了。

static\img\rand
貌似只能20张。我添加到40张，多出来的不会显示。序号也排好了。发了很多测试文章都没有显示我添加的图片。发现是${show_thumb(article)}，这里面article的cid确定图片的路径，应该怎么才能改动最大的cid，让它能显示我自己的图片呢？

**Comment by biezhi** [comment]
这个就需要修改一点源码了，你可以修改 [这里](https://github.com/otale/tale/blob/master/src/main/java/com/tale/extension/Theme.java#L335)

**Comment by OuGaoJun** [comment]
大佬，刚才我在后台点进主题设置，然后点了一下保存主题，发现主页崩了：
![tim 20171101145801](https://user-images.githubusercontent.com/31914181/32263483-1cbf1df8-bf15-11e7-9bec-5df84ec69b87.jpg)

然后后台的主题设置按钮点进去也崩了：
![image](https://user-images.githubusercontent.com/31914181/32263500-29f5c97c-bf15-11e7-9de1-051edd5eba72.png)
![image](https://user-images.githubusercontent.com/31914181/32263509-31224f18-bf15-11e7-8121-a8162014bca9.png)

**Comment by biezhi** [comment]
@OuGaoJun 看看日志有什么报错吗 `./tale-cli log`

**Comment by OuGaoJun** [comment]
重启服务器也进不去主页了。我现在给你发log

**Comment by OuGaoJun** [comment]
```
2017-11-01 15:00:41:528 INFO - [ _(:3」∠)_ ] c.b.s.n.NettyServer       | ? Register bean: [com.blade.Environment@309fcd6a, com.tale.init.WebContext@5884d271, com.tale.service.ContentsService@430f11c4, com.tale.exception.GolbalExceptionHandler@2c8e55f2, com.tale.controller.admin.AuthController@62343994, com.tale.service.SiteService@1cdd78f9, com.tale.service.OptionsService@27e7db97, com.tale.controller.admin.ThemeController@79983b5c, com.tale.controller.admin.CategoryController@3aa35562, com.tale.controller.IndexController@4dcee87f, com.tale.controller.CategoryController@54eca932, com.tale.controller.admin.AttachController@6c162a28, com.tale.service.CommentsService@4cbe6a8d, com.tale.hooks.BaseWebHook@7689ee75, com.tale.controller.admin.PageController@479d7caf, com.tale.controller.admin.IndexController@1a07491e, com.tale.controller.admin.CommentController@25d2a2d1, com.tale.controller.InstallController@1c111a58, com.tale.service.MetasService@30456571, com.tale.init.WebContext@5884d271, com.tale.controller.admin.ArticleController@102a95de, com.tale.hooks.BaseWebHook@7689ee75, com.tale.controller.admin.TemplateController@205e7920]
2017-11-01 15:00:41:669 INFO - [ _(:3」∠)_ ] j.t.JetEngineImpl         | JetEngine.version = 2.1.5
2017-11-01 15:00:41:669 INFO - [ _(:3」∠)_ ] j.t.JetEngineImpl         | JetEngine.loader = jetbrick.template.loader.ClasspathResourceLoader, root = /templates/, reload = true
2017-11-01 15:00:41:684 INFO - [ _(:3」∠)_ ] j.t.r.c.ClassResolver     | import package: java.lang.*
2017-11-01 15:00:41:684 INFO - [ _(:3」∠)_ ] j.t.r.c.ClassResolver     | import package: java.util.*
2017-11-01 15:00:41:700 INFO - [ _(:3」∠)_ ] j.t.r.m.MethodInvokerResolver | import 38 methods from class jetbrick.template.runtime.buildin.JetMethods
2017-11-01 15:00:41:700 INFO - [ _(:3」∠)_ ] j.t.r.f.FunctionInvokerResolver | import 11 functions from class jetbrick.template.runtime.buildin.JetFunctions
2017-11-01 15:00:41:700 INFO - [ _(:3」∠)_ ] j.t.r.t.TagInvokerResolver | import 2 tags from class jetbrick.template.runtime.buildin.JetTags
2017-11-01 15:00:41:700 INFO - [ _(:3」∠)_ ] j.t.r.GlobalResolver      | Scanning @JetMethods, @JetFunctions, @JetTags implements from [com.tale] ...
2017-11-01 15:00:41:809 INFO - [ _(:3」∠)_ ] j.t.r.GlobalResolver      | Found 0 annotated classes, time elapsed 94 ms.
2017-11-01 15:00:41:840 INFO - [ _(:3」∠)_ ] j.t.JetTemplateImpl       | Loading template: /comm/macros.html
2017-11-01 15:00:42:075 INFO - [ _(:3」∠)_ ] j.t.r.f.FunctionInvokerResolver | import 21 functions from class com.tale.extension.Commons
2017-11-01 15:00:42:075 INFO - [ _(:3」∠)_ ] j.t.r.f.FunctionInvokerResolver | import 50 functions from class com.tale.extension.Theme
2017-11-01 15:00:42:090 INFO - [ _(:3」∠)_ ] j.t.r.f.FunctionInvokerResolver | import 2 functions from class com.tale.extension.AdminCommons
2017-11-01 15:00:42:090 INFO - [ _(:3」∠)_ ] j.t.r.t.TagInvokerResolver | import 1 tags from class com.tale.extension.JetTag
2017-11-01 15:00:42:090 DEBUG - [ _(:3」∠)_ ] c.b.j.c.ActiveRecord      | ? Execute SQL => select * from t_options
2017-11-01 15:00:42:106 DEBUG - [ _(:3」∠)_ ] c.b.j.c.ActiveRecord      | ? Parameters  => []
2017-11-01 15:00:42:247 INFO - [ _(:3」∠)_ ] c.b.s.n.NettyServer       | ? Use NioEventLoopGroup
2017-11-01 15:00:42:465 INFO - [ _(:3」∠)_ ] c.b.s.n.NettyServer       | ? Tale (塌了) initialize successfully, Time elapsed: 1718 ms
2017-11-01 15:00:42:465 INFO - [ _(:3」∠)_ ] c.b.s.n.NettyServer       | ? Blade start with 0.0.0.0:80
2017-11-01 15:00:42:465 INFO - [ _(:3」∠)_ ] c.b.s.n.NettyServer       | ? Open your web browser and navigate to http://127.0.0.1:80 ?
2017-11-01 15:01:04:528 INFO - [ worker@pool thread-1 ] c.b.s.n.HttpServerHandler | HTTP/1.1	GET	/
2017-11-01 15:01:04:590 INFO - [ worker@pool thread-1 ] c.t.h.BaseWebHook         | UserAgent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36
2017-11-01 15:01:04:590 INFO - [ worker@pool thread-1 ] c.t.h.BaseWebHook         | 用户访问地址: /, 来路地址: 127.0.0.1
2017-11-01 15:01:04:590 DEBUG - [ worker@pool thread-1 ] c.b.j.c.ActiveRecord      | ? Execute SQL => select * from t_users where uid = :p1
2017-11-01 15:01:04:590 DEBUG - [ worker@pool thread-1 ] c.b.j.c.ActiveRecord      | ? Parameters  => [1]
2017-11-01 15:01:04:637 INFO - [ worker@pool thread-1 ] j.t.JetTemplateImpl       | Loading template: themes/default/index.html
2017-11-01 15:01:04:669 INFO - [ worker@pool thread-1 ] j.t.JetTemplateImpl       | Loading template: themes/default/partial/header.html
2017-11-01 15:01:04:825 ERROR - [ worker@pool thread-1 ] c.b.m.h.HttpResponse      | render error
com.blade.exception.TemplateException: jetbrick.template.runtime.InterpretException: function invoke error: com.tale.extension.Theme#theme_option(java.lang.String)

template: themes/default/partial/header.html: 33,16
-------------------------------------------------------------------------------
 31:     <div class="navbar-container">
 32:         <a href="${site_url()}" class="navbar-logo">
 33:             #if(theme_option('logo_url') == "")
                     ^ -- here
 34:             <img src="${theme_url('/static/img/logo.png')}" alt="${site_title()}"/>
 35:             #else
-------------------------------------------------------------------------------

	at com.blade.mvc.view.template.JetbrickTemplateEngine.render(JetbrickTemplateEngine.java:105)
	at com.blade.mvc.http.HttpResponse.render(HttpResponse.java:200)
	at com.blade.mvc.http.Response.render(Response.java:272)
	at com.blade.mvc.handler.RequestInvoker.handle(RequestInvoker.java:92)
	at com.blade.mvc.handler.RequestInvoker.routeHandle(RequestInvoker.java:55)
	at com.blade.server.netty.HttpServerHandler.channelRead0(HttpServerHandler.java:108)
	at com.blade.server.netty.HttpServerHandler.channelRead0(HttpServerHandler.java:34)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.handler.codec.http.HttpServerExpectContinueHandler.channelRead(HttpServerExpectContinueHandler.java:95)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: jetbrick.template.runtime.InterpretException: function invoke error: com.tale.extension.Theme#theme_option(java.lang.String)

template: themes/default/partial/header.html: 33,16
-------------------------------------------------------------------------------
 31:     <div class="navbar-container">
 32:         <a href="${site_url()}" class="navbar-logo">
 33:             #if(theme_option('logo_url') == "")
                     ^ -- here
 34:             <img src="${theme_url('/static/img/logo.png')}" alt="${site_title()}"/>
 35:             #else
-------------------------------------------------------------------------------

	at jetbrick.template.parser.ast.AstInvokeFunction.doInvoke(AstInvokeFunction.java:94)
	at jetbrick.template.parser.ast.AstInvokeFunction.execute(AstInvokeFunction.java:54)
	at jetbrick.template.parser.ast.AstOperatorEquals.execute(AstOperatorEquals.java:39)
	at jetbrick.template.parser.ast.AstDirectiveIf.execute(AstDirectiveIf.java:38)
	at jetbrick.template.parser.ast.AstStatementList.execute(AstStatementList.java:212)
	at jetbrick.template.parser.ast.AstTemplate.execute(AstTemplate.java:37)
	at jetbrick.template.runtime.InterpretContextImpl.doIncludeCall(InterpretContextImpl.java:132)
	at jetbrick.template.parser.ast.AstDirectiveInclude.execute(AstDirectiveInclude.java:67)
	at jetbrick.template.parser.ast.AstStatementList.execute(AstStatementList.java:212)
	at jetbrick.template.parser.ast.AstTemplate.execute(AstTemplate.java:37)
	at jetbrick.template.JetTemplateImpl.doInterpret(JetTemplateImpl.java:160)
	at jetbrick.template.JetTemplateImpl.render(JetTemplateImpl.java:141)
	at com.blade.mvc.view.template.JetbrickTemplateEngine.render(JetbrickTemplateEngine.java:103)
	... 43 more
Caused by: com.blade.kit.json.ParseException: s/themes\d  (111):Illegal escape.
	at com.blade.kit.json.JsonSerializer.nextValue(JsonSerializer.java:195)
	at com.blade.kit.json.JsonSerializer.nextValue(JsonSerializer.java:94)
	at com.blade.kit.json.JsonSerializer.deserialize(JsonSerializer.java:72)
	at com.blade.kit.JsonKit.toAson(JsonKit.java:35)
	at com.tale.extension.Theme.lambda$theme_option$0(Theme.java:701)
	at java.util.Optional.map(Unknown Source)
	at com.tale.extension.Theme.theme_option(Theme.java:700)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at jetbrick.bean.MethodInfo.invoke(MethodInfo.java:202)
	at jetbrick.template.resolver.function.ExtensionFunctionInvoker.invoke(ExtensionFunctionInvoker.java:54)
	at jetbrick.template.parser.ast.AstInvokeFunction.doInvoke(AstInvokeFunction.java:85)
	... 55 more

```

**Comment by biezhi** [comment]
你在设置主题信息的时候填的什么内容？

**Comment by OuGaoJun** [comment]
没改东西，就是默认的。然后点了确认提示操作成功，然后就挂了。。

**Comment by OuGaoJun** [comment]
我当时看了一样那个主题路径，好像含有正斜杠和反斜杠，挺奇怪的东西。不知道是不是这个导致的问题。现在我进不去了，看不了

**Comment by OuGaoJun** [comment]
已经发了一份数据库文件到 biezhi.me@gmail.com

**Comment by OuGaoJun** [comment]
我把数据库这一行删掉就没事了。应该是数据问题。
![tim 20171101145801](https://user-images.githubusercontent.com/31914181/32267423-33194680-bf26-11e7-89e1-8cdf55bce809.jpg)

数据内容：
```
name:
theme_default_options
value：
{"social_zhihu":"","social_github":"","social_twitter":"","logo_url":"http://www.ougaojun.com/templates/themes\default/static/img/logo.png","author":"biezhi","social_weibo":""}
```

**Comment by biezhi** [comment]
就是这个配置引起的问题，不过修改正常就好了。这是一个 `bug`，即将修复它。
