### ISSUE TITLE
mvn package打包之后java -jar tale.jar找不到类

### ISSUE THREAD

**Issue by smartning** [otale/tale#328]
我只在mysql那个分支开发的

D:\work\tale\target>java -jar tale.jar
Exception in thread "main" java.lang.NoClassDefFoundError: com/blade/Blade
        at com.tale.init.TaleLoader.init(TaleLoader.java:25)
        at com.tale.Application.main(Application.java:10)
Caused by: java.lang.ClassNotFoundException: com.blade.Blade
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 2 more

**Comment by smartning** [comment]
问题已经解决，在pom中缺少了：
`<executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>`

测试可行

**Comment by ted-wq-x** [comment]
解决的话，把这个issue关掉吧
