### ISSUE TITLE
重启报错

### ISSUE THREAD

**Issue by p1094358629** [otale/tale#340]
com.blade.exception.BladeException: java.lang.NullPointerException
	at com.blade.mvc.view.resolve.RouteViewResolve.handle(RouteViewResolve.java:72)
	at com.blade.mvc.dispatch.DispatcherHandler.routeHandle(DispatcherHandler.java:184)
	at com.blade.mvc.dispatch.DispatcherHandler.handle(DispatcherHandler.java:94)
	at com.blade.mvc.dispatch.DispatcherServlet.service(DispatcherServlet.java:39)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:830)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:543)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1584)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1228)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1553)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1130)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:318)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.blade.jdbc.ar.SampleActiveRecord.page(SampleActiveRecord.java:385)
	at com.tale.service.impl.ContentsServiceImpl.getContentsPage(ContentsServiceImpl.java:44)
	at com.tale.service.impl.ContentsServiceImpl.getArticles(ContentsServiceImpl.java:50)
	at com.tale.controller.IndexController.index(IndexController.java:103)
	at com.tale.controller.IndexController.index(IndexController.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.blade.kit.reflect.ReflectKit.invokeMehod(ReflectKit.java:316)
	at com.blade.mvc.view.resolve.RouteViewResolve.handle(RouteViewResolve.java:51)
	... 30 more
[tale] 2018-01-19 09:12:09,186 INFO  [blade-pool-24] jetbrick.template.JetTemplateImpl | Loading template: /comm/error_500.html

**Comment by p1094358629** [comment]
好几次了,只能重装才能解决么?
