### ISSUE TITLE
SQLLITE ERROR

### ISSUE THREAD

**Issue by dawn-zhao** [otale/tale#357]
org.sql2o.Sql2oException: Error preparing statement - [SQLITE_ERROR] SQL error or missing database (near "null": syntax error)
	at com.tale.service.ContentsService.getArticles(ContentsService.java:162)
	at com.tale.controller.CategoryController.categories(CategoryController.java:70)
	at com.tale.controller.CategoryController.categories(CategoryController.java:55)

**Comment by biezhi** [comment]
[fixed](https://github.com/otale/tale/commit/47112e87c8adf58fab20c6baec30749fe809ba0e)
```bash
git pull
```
