### ISSUE TITLE
主页点击文章分类出现sql异常

### ISSUE THREAD

**Issue by imn5100** [otale/tale#370]
(develop分支)安装完成后，直接访问http://127.0.0.1:9000/category/%E9%BB%98%E8%AE%A4%E5%88%86%E7%B1%BB
出现异常：
`org.sql2o.Sql2oException: Error preparing statement - [SQLITE_ERROR] SQL error or missing database (near "null": syntax error)`
部分异常栈：
`	at io.github.biezhi.anima.core.AnimaQuery.pageBySQL(AnimaQuery.java:420)
	at io.github.biezhi.anima.core.dml.Select.pageBySQL(Select.java:49)
	at com.tale.service.ContentsService.getArticles(ContentsService.java:163)
	at com.tale.controller.CategoryController.categories(CategoryController.java:70)
	at com.tale.controller.CategoryController.categories(CategoryController.java:55)`

**Comment by imn5100** [comment]
更新最新代码已解决，Thanks。
