### ISSUE TITLE
在上传无后缀文件的时候，是上传失败的

### ISSUE THREAD

**Issue by y191881708** [otale/tale#391]
在上传无后缀文件的时候，是上传失败的。日志如下
2018-05-29 14:51:40:941 INFO - [ nio-worker@ thread-2 ] c.b.m.h.RequestExecution  | HTTP/1.1    POST    /admin/attach/upload
2018-05-29 14:51:40:941 INFO - [ nio-worker@ thread-2 ] c.t.h.BaseWebHook         | UserAgent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
2018-05-29 14:51:40:941 INFO - [ nio-worker@ thread-2 ] c.t.h.BaseWebHook         | 用户访问地址: /admin/attach/upload, 来路地址: x.x.x.x
2018-05-29 14:51:40:941 INFO - [ nio-worker@ thread-2 ] c.t.c.a.AttachController  | UPLOAD DIR = /main/tale/resources
2018-05-29 14:51:40:942 ERROR - [ nio-worker@ thread-2 ] c.t.c.a.AttachController  | 文件上传失败
java.lang.NullPointerException
        at com.tale.controller.admin.AttachController.lambda$upload$0(AttachController.java:97)
        at java.util.HashMap$Values.forEach(HashMap.java:981)
        at com.tale.controller.admin.AttachController.upload(AttachController.java:91)
        at sun.reflect.GeneratedMethodAccessor209.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.blade.kit.ReflectKit.invokeMethod(ReflectKit.java:89)
        at com.blade.mvc.handler.RequestExecution.handle(RequestExecution.java:171)
        at com.blade.mvc.handler.RequestExecution.routeHandle(RequestExecution.java:142)
        at com.blade.mvc.handler.RequestExecution.run(RequestExecution.java:108)
        at com.blade.server.netty.HttpServerHandler.channelRead0(HttpServerHandler.java:26)
        at com.blade.server.netty.HttpServerHandler.channelRead0(HttpServerHandler.java:18)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.handler.codec.http.HttpServerExpectContinueHandler.channelRead(HttpServerExpectContinueHandler.java:95)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Thread.java:748)

**Comment by zoujiayu** [comment]
这个出于安全考虑应该是做了判断
将附件直接上传upload文件夹
然后            博客地址/upload/附件名         即可访问

ps.手动上传的文件，在后台附件管理是不会有显示的。

**Comment by zoujiayu** [comment]
也有上传附件的大小限制
public static Integer MAX_FILE_SIZE = 204800;

**Comment by zoujiayu** [comment]
忘了，还有附件大小的限制
public static Integer MAX_FILE_SIZE = 204800;

204800/1024
