### ISSUE TITLE
mvn打包并运行问题

### ISSUE THREAD

**Issue by troyforever** [otale/tale#392]
git clone tale源码后
运行mvn package打包成tale.jar文件
java -jar tale.jar运行时
错误提示：
`
Exception in thread "main" java.lang.NoClassDefFoundError: com/blade/Blade
        at com.tale.Application.main(Application.java:16)
Caused by: java.lang.ClassNotFoundException: com.blade.Blade
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 1 more
`

**Comment by pjc516113732** [comment]
同问

**Comment by GodChuan88** [comment]
同问 有没有解决方法

**Comment by GodChuan88** [comment]
@biezhi

**Comment by DerrickYang007** [comment]
不是应该达成war包到tomcat里面运行吗

**Comment by biezhi** [comment]
查看 [wiki](https://github.com/otale/tale/wiki/02.-%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83%E4%B8%8B%E8%BF%90%E8%A1%8C)
