### ISSUE TITLE
启动的时候报错，SQL错误

### ISSUE THREAD

**Issue by wanbao666** [otale/tale#407]
2018/07/04 17:24:38 DEBUG [   worker@threadㄧ1 ]                       o.s.Query : Parameters  => [null, 初始化站点, null, 1, , 1530696278]
2018/07/04 17:24:38 DEBUG [   worker@threadㄧ1 ]                       o.s.Query : total: 150 ms; executed update [No name]
2018/07/04 17:24:38 ERROR [   worker@threadㄧ1 ]    c.b.s.n.HttpServerDispatcher :  500          POST   /install
2018/07/04 17:24:38 ERROR [   worker@threadㄧ1 ] c.b.m.h.DefaultExceptionHandler : Request Exception io.github.biezhi.anima.exception.AnimaException
	at io.github.biezhi.anima.core.AnimaCache.lambda$getLambdaColumnName$6(AnimaCache.java:124)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1127)
	at io.github.biezhi.anima.core.AnimaCache.getLambdaColumnName(AnimaCache.java:116)
	at io.github.biezhi.anima.utils.AnimaUtils.getLambdaColumnName(AnimaUtils.java:160)
	at io.github.biezhi.anima.core.AnimaQuery.where(AnimaQuery.java:234)
	at com.tale.service.OptionsService.saveOption(OptionsService.java:35)
	at com.tale.controller.InstallController.doInstall(InstallController.java:65)
	at com.tale.controller.InstallControllerMethodAccess.invoke(Unknown Source)
	at com.blade.reflectasm.MethodAccess.invoke(MethodAccess.java:43)
	at com.blade.server.netty.RouteMethodHandler.routeHandle(RouteMethodHandler.java:200)
	at com.blade.server.netty.RouteMethodHandler.handle(RouteMethodHandler.java:330)
	at com.blade.server.netty.HttpServerDispatcher.channelRead0(HttpServerDispatcher.java:68)
	at com.blade.server.netty.HttpServerDispatcher.channelRead0(HttpServerDispatcher.java:36)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.handler.codec.http.HttpServerExpectContinueHandler.channelRead(HttpServerExpectContinueHandler.java:95)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchFieldException: lambda$0
	at java.lang.Class.getDeclaredField(Class.java:2070)
	at io.github.biezhi.anima.core.AnimaCache.lambda$getLambdaColumnName$6(AnimaCache.java:121)
	... 47 more

2018/07/04 17:24:38  INFO [   worker@threadㄧ1 ]             j.t.JetTemplateImpl : Loading template: /comm/error_500.html

**Comment by pjc516113732** [comment]
已经解决改个代码
SiteServiceImpl

Long uid = Long.parseLong(activeRecord.insert(users) + "");

**Comment by biezhi** [comment]
那我关闭这个 `issue` 了。
