### ISSUE TITLE
大神问下,这个报错是什么情况

### ISSUE THREAD

**Issue by fireflyhoo** [otale/tale#413]
![image](https://user-images.githubusercontent.com/3061324/42942819-aae8a9fa-8b93-11e8-8902-ab928ea287e7.png)

**Comment by fireflyhoo** [comment]
![image](https://user-images.githubusercontent.com/3061324/42942969-19e2ae5a-8b94-11e8-84b5-3ebb49009d34.png)

**Comment by biezhi** [comment]
@fireflyhoo 控制台的异常是什么？你如何让它重现的？

**Comment by fireflyhoo** [comment]
下载代码 mac下 eclipse debug运行 , 控制台压测是  找不到这个属性

**Comment by fireflyhoo** [comment]
[37m2018/07/21 22:29:31 [0m[32m[1m INFO[0m [37m[   worker@threadㄧ1 ] [0m[34m            j.t.JetTemplateImpl : [0mLoading template: themes/default/partial/header.html
[37m2018/07/21 22:29:50 [0m[31m[1mERROR[0m [37m[   worker@threadㄧ1 ] [0m[34m     c.b.s.n.RouteMethodHandler : [0mRender view error com.blade.exception.TemplateException: jetbrick.template.runtime.InterpretException: function invoke error: com.tale.extension.Theme#articles(int)

template: themes/default/index.html: 5,27
-------------------------------------------------------------------------------
  3:     <div class="post-lists">
  4:         <div class="post-lists-body">
  5:             #for(article : articles(12).rows)
                                ^ -- here
  6:             <div class="post-list-item">
  7:                 <div class="post-list-item-container">
-------------------------------------------------------------------------------

	at com.blade.mvc.view.template.JetbrickTemplateEngine.render(JetbrickTemplateEngine.java:105)
	at com.blade.server.netty.RouteMethodHandler$1.onView(RouteMethodHandler.java:80)
	at com.blade.server.netty.RouteMethodHandler$1.onView(RouteMethodHandler.java:62)
	at com.blade.mvc.http.ViewBody.write(ViewBody.java:19)
	at com.blade.server.netty.RouteMethodHandler.handleResponse(RouteMethodHandler.java:62)
	at com.blade.server.netty.HttpServerDispatcher.finishWrite(HttpServerDispatcher.java:91)
	at com.blade.server.netty.HttpServerDispatcher.channelRead0(HttpServerDispatcher.java:75)
	at com.blade.server.netty.HttpServerDispatcher.channelRead0(HttpServerDispatcher.java:34)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.handler.codec.http.HttpServerExpectContinueHandler.channelRead(HttpServerExpectContinueHandler.java:95)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Thread.java:748)
Caused by: jetbrick.template.runtime.InterpretException: function invoke error: com.tale.extension.Theme#articles(int)

template: themes/default/index.html: 5,27
-------------------------------------------------------------------------------
  3:     <div class="post-lists">
  4:         <div class="post-lists-body">
  5:             #for(article : articles(12).rows)
                                ^ -- here
  6:             <div class="post-list-item">
  7:                 <div class="post-list-item-container">
-------------------------------------------------------------------------------

	at jetbrick.template.parser.ast.AstInvokeFunction.doInvoke(AstInvokeFunction.java:94)
	at jetbrick.template.parser.ast.AstInvokeFunction.execute(AstInvokeFunction.java:54)
	at jetbrick.template.parser.ast.AstInvokeField.execute(AstInvokeField.java:47)
	at jetbrick.template.parser.ast.AstDirectiveFor.execute(AstDirectiveFor.java:42)
	at jetbrick.template.parser.ast.AstStatementList.execute(AstStatementList.java:212)
	at jetbrick.template.parser.ast.AstTemplate.execute(AstTemplate.java:37)
	at jetbrick.template.JetTemplateImpl.doInterpret(JetTemplateImpl.java:160)
	at jetbrick.template.JetTemplateImpl.render(JetTemplateImpl.java:141)
	at com.blade.mvc.view.template.JetbrickTemplateEngine.render(JetbrickTemplateEngine.java:103)
	... 42 more
Caused by: io.github.biezhi.anima.exception.AnimaException
	at io.github.biezhi.anima.core.AnimaCache.lambda$getLambdaColumnName$6(AnimaCache.java:124)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1127)
	at io.github.biezhi.anima.core.AnimaCache.getLambdaColumnName(AnimaCache.java:116)
	at io.github.biezhi.anima.utils.AnimaUtils.getLambdaColumnName(AnimaUtils.java:160)
	at io.github.biezhi.anima.core.AnimaQuery.where(AnimaQuery.java:234)
	at com.tale.extension.Theme.articles(Theme.java:642)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at jetbrick.bean.MethodInfo.invoke(MethodInfo.java:201)
	at jetbrick.template.resolver.function.ExtensionFunctionInvoker.invoke(ExtensionFunctionInvoker.java:54)
	at jetbrick.template.parser.ast.AstInvokeFunction.doInvoke(AstInvokeFunction.java:85)
	... 50 more
Caused by: java.lang.NoSuchFieldException: lambda$0
	at java.lang.Class.getDeclaredField(Class.java:2070)
	at io.github.biezhi.anima.core.AnimaCache.lambda$getLambdaColumnName$6(AnimaCache.java:121)
	... 62 more

**Comment by biezhi** [comment]
@fireflyhoo 代码格式有点乱，要不你试试 `git pull` 拉一下代码看有没有这个问题。

**Comment by fireflyhoo** [comment]
我在window上和liunx跑貌似没有问题.

**Comment by biezhi** [comment]
@fireflyhoo 😂 我也是 mac 环境

**Comment by fireflyhoo** [comment]
![image](https://user-images.githubusercontent.com/3061324/44135249-ea668a0e-a09a-11e8-8b41-b26749d061cd.png)
![image](https://user-images.githubusercontent.com/3061324/44135254-f1cb8254-a09a-11e8-9be1-6dcb0b22176a.png)
![image](https://user-images.githubusercontent.com/3061324/44135313-2b7b6c08-a09b-11e8-84cd-a6f186bf4199.png)
难道是我的电脑有毒😢
