### ISSUE TITLE
博客性能问题反馈

### ISSUE THREAD

**Issue by parasomn1a** [otale/tale#420]
#  问题描述
1. 使用sqlite如何保证并发性能？
当博客的并发量较大时会出现异常
2. 如何反垃圾评论
根据源码，评论是通过ip+文章编号的方式来判断，在30s内不能重复留言，但是无法阻止垃圾评论脚本，有什么办法能阻止这些脚本呢？

#  使用环境
1. Ubuntu 18.04+nginx 1.14，使用https

**Comment by zoujiayu** [comment]
1.出现的异常能列举下吗
   Tale使用blade框架，blade基于netty，本身并发就不错的
   sqlite比mysql的并发本身就高很多
2.反垃圾评论，可以写成插件或集成在tale评论模块，作者应该会考虑这个需求。

**Comment by MuenYu** [comment]
@zoujiayu 感谢你的回复

异常信息
```
	at com.blade.mvc.view.template.JetbrickTemplateEngine.render(JetbrickTemplateEngine.java:105)
	at com.blade.mvc.http.HttpResponse.render(HttpResponse.java:198)
	at com.blade.mvc.http.Response.render(Response.java:274)
	at com.blade.mvc.handler.RequestExecution.handle(RequestExecution.java:179)
	at com.blade.mvc.handler.RequestExecution.routeHandle(RequestExecution.java:142)
	at com.blade.mvc.handler.RequestExecution.run(RequestExecution.java:108)
	at com.blade.server.netty.HttpServerHandler.channelRead0(HttpServerHandler.java:26)
	at com.blade.server.netty.HttpServerHandler.channelRead0(HttpServerHandler.java:18)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.handler.codec.http.HttpServerExpectContinueHandler.channelRead(HttpServerExpectContinueHandler.java:95)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
Caused by: jetbrick.template.runtime.InterpretException: function invoke error: com.tale.extension.Theme#comments(int)

template: themes/default/partial/comments.html: 27,25
-------------------------------------------------------------------------------
 25:         #end
 26: 
 27:         #set( comments = comments(6) )
                              ^ -- here
 28: 
 29:         #if(!is_empty(comments))
-------------------------------------------------------------------------------

	at jetbrick.template.parser.ast.AstInvokeFunction.doInvoke(AstInvokeFunction.java:94)
	at jetbrick.template.parser.ast.AstInvokeFunction.execute(AstInvokeFunction.java:54)
	at jetbrick.template.parser.ast.AstDirectiveSet.execute(AstDirectiveSet.java:37)
	at jetbrick.template.parser.ast.AstStatementList.execute(AstStatementList.java:212)
	at jetbrick.template.parser.ast.AstDirectiveIf.execute(AstDirectiveIf.java:40)
	at jetbrick.template.parser.ast.AstStatementList.execute(AstStatementList.java:212)
	at jetbrick.template.parser.ast.AstTemplate.execute(AstTemplate.java:37)
	at jetbrick.template.runtime.InterpretContextImpl.doIncludeCall(InterpretContextImpl.java:132)
	at jetbrick.template.parser.ast.AstDirectiveInclude.execute(AstDirectiveInclude.java:67)
	at jetbrick.template.parser.ast.AstStatementList.execute(AstStatementList.java:212)
	at jetbrick.template.parser.ast.AstTemplate.execute(AstTemplate.java:37)
	at jetbrick.template.JetTemplateImpl.doInterpret(JetTemplateImpl.java:160)
	at jetbrick.template.JetTemplateImpl.render(JetTemplateImpl.java:141)
	at com.blade.mvc.view.template.JetbrickTemplateEngine.render(JetbrickTemplateEngine.java:103)
	... 42 more
Caused by: org.sql2o.Sql2oException: Error preparing statement - [SQLITE_ERROR] SQL error or missing database (near "ORDER": syntax error)
	at org.sql2o.Query.buildPreparedStatement(Query.java:426)
	at org.sql2o.Query.buildPreparedStatement(Query.java:408)
	at org.sql2o.Query$ResultSetIterableBase.<init>(Query.java:461)
	at org.sql2o.Query$14.<init>(Query.java:545)
	at org.sql2o.Query.executeAndFetchLazy(Query.java:545)
	at org.sql2o.Query.executeAndFetch(Query.java:587)
	at org.sql2o.Query.executeAndFetch(Query.java:574)
	at com.blade.jdbc.core.ActiveRecord.queryAll(ActiveRecord.java:192)
	at com.blade.jdbc.core.ActiveRecord.queryAll(ActiveRecord.java:169)
	at com.blade.jdbc.core.ActiveRecord.page(ActiveRecord.java:259)
	at com.blade.jdbc.core.ActiveRecord.page(ActiveRecord.java:232)
	at com.blade.jdbc.core.ActiveRecord.page(ActiveRecord.java:223)
	at com.tale.service.CommentsService.getComments(CommentsService.java:89)
	at com.tale.service.SiteService.getComments(SiteService.java:298)
	at com.tale.extension.Theme.comments(Theme.java:621)
	at jetbrick.bean.asm.delegate.com_tale_extension_Theme.invoke(Unknown Source)
	at jetbrick.bean.MethodInfo.invoke(MethodInfo.java:207)
	at jetbrick.template.resolver.function.ExtensionFunctionInvoker.invoke(ExtensionFunctionInvoker.java:54)
	at jetbrick.template.parser.ast.AstInvokeFunction.doInvoke(AstInvokeFunction.java:85)
	... 55 more
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (near "ORDER": syntax error)
	at org.sqlite.core.DB.newSQLException(DB.java:909)
	at org.sqlite.core.DB.newSQLException(DB.java:921)
	at org.sqlite.core.DB.throwex(DB.java:886)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:127)
	at org.sqlite.core.DB.prepare(DB.java:227)
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:41)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19)
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:48)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:254)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:226)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:233)
	at org.sql2o.Query.buildPreparedStatement(Query.java:421)
	... 73 more
```

**Comment by zoujiayu** [comment]
@MuenYu 
可以尝试用nginx，并发比Apache好的多
tale大多是静态页面，没必要用Apache
nginx是异步非堵塞，Apache是异步堵塞。
具体可以[百度](baidu.com)

**Comment by zoujiayu** [comment]
@MuenYu 
可以尝试用nginx，并发比Apache好的多
tale大多是静态页面，没必要用Apache
nginx是异步非堵塞，Apache是同步堵塞。
具体可以[百度](baidu.com)

**Comment by zoujiayu** [comment]
之前也用Apache Benchmark在本地跑过压力测试，并发还不错
这个问题就给作者解决吧
@biezhi 接锅

**Comment by biezhi** [comment]
@MuenYu 感谢你反馈这个问题，可以发下你  ab 测试的具体参数吗？之前确实没有测试过并发这个问题，如果重现我将在后续版本中优化它。关于评论垃圾这个问题之前有考虑过，但 tale 本身还无法智能的处理它们，所以我的想法是支持以插件的形式让对这块熟悉的人来扩展它。

**Comment by MuenYu** [comment]
```
ab -c 500 -t 60 http://127.0.0.1/article/2/
```
使用的是比较老的版本(5.16fork的)

顺带一提，在代码重构后的新tale上，有性能提升吗？
