### ISSUE TITLE
”下载“链接的wiki 【01. 如何使用Tale】页面的zip包， 执行java -jar tale-least.jar 报错.

### ISSUE THREAD

**Issue by DerrickYang007** [otale/tale#428]
cmd里面运行的。
Exception in thread "main" java.lang.NullPointerException
	at com.tale.init.TaleLoader.loadThemes(TaleLoader.java:33)
	at com.tale.init.TaleLoader.init(TaleLoader.java:27)
	at com.tale.Application.main(Application.java:17)

**Comment by biezhi** [comment]
你看了 [这个](https://github.com/otale/tale/wiki/02.-%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83%E4%B8%8B%E8%BF%90%E8%A1%8C) 吗？

**Comment by aijoo2012** [comment]
含有中文目录。导致
