### ISSUE TITLE
IOException: 远程主机强迫关闭了一个现有的连接

### ISSUE THREAD

**Issue by pl1612127** [otale/tale#507]
`
2018/12/17 19:29:34 ERROR [   worker@threadㄧ1 ]    c.b.s.n.HttpServerDispatcher : 远程主机强迫关闭了一个现有的连接。 java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:628)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:563)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by biezhi** [comment]
@pl1612127 这个情况应该是在 Windows 下发生的，不过不会影响应用使用。

**Comment by biezhi** [comment]
@pl1612127 `tale` 试图带着 Java 开发者做一点思维上的转变，我们并非 Spring 的奴隶。当然有很多人基于 Spring 系的框架做了实现，同样也受欢迎。

实际上用哪个框架并不是特别的重要，只要文档齐全不闭源，流行的软件框架都可以实现效果，学习的只是设计和思想。

即便不是 Blade，一样也要操作模板引擎，比如 `Vert.X`、`Play`，只不过可能是你熟悉的而已。`Jetbrick` 库并没有多大的学习成本（只要你熟悉模板的操作），像它自己所说：

> jetbrick-template 是一个新一代 Java 模板引擎，具有高性能和高扩展性。 适合于动态 HTML 页面输出或者代码生成，可替代 JSP 页面或者 Velocity 等模板。 指令和 Velocity 相似，表达式和 Java 保持一致，易学易用。

我认为你所说的 “价值” 是所有人都认同的一种开发模式或体系，这在我看来过于死板。如果你愿意接受新的尝试那肯定需要花费一些精力，当然如果想二次开发，可以搜到很多基于 tale 实现的 Spring 版本。

**Comment by pl1612127** [comment]
你这个想法没问题的 ，挺好 。只是国内做开源很辛苦 ，少点技术壁垒会不会参与的人更多 ，让圈子更活跃

**Comment by biezhi** [comment]
@pl1612127 起初我认为开源需要的是更多人参与，在我看来它是一种精神、一种信仰，并非所有人都乐于此，大家都会想：谁愿意免费的为全世界的程序员打工呢？

不过这个 issue 我们不讨论这个问题了，该回答的已经回复了，我关闭了这个 issue 哈。
