### ISSUE TITLE
IOException: 文件名过长

### ISSUE THREAD

**Issue by pl1612127** [otale/tale#509]
```
2018/12/18 13:46:55 ERROR [   worker@thread-2 ]       c.b.s.n.HttpServerHandler :  500          GET /templates/themes/default/static/js/headroom.min.js
2018/12/18 13:46:55 ERROR [   worker@thread-2 ] c.b.m.h.DefaultExceptionHandler :  io.netty.handler.codec.http.multipart.HttpPostRequestDecoder$ErrorDataDecoderException: java.io.IOException: 文件名过长
	at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.parseBodyAttributes(HttpPostStandardRequestDecoder.java:605)
	at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.parseBody(HttpPostStandardRequestDecoder.java:360)
	at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.offer(HttpPostStandardRequestDecoder.java:289)
	at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.offer(HttpPostStandardRequestDecoder.java:46)
	at io.netty.handler.codec.http.multipart.HttpPostRequestDecoder.offer(HttpPostRequestDecoder.java:227)
	at com.blade.mvc.http.HttpRequest.init(HttpRequest.java:359)
	at com.blade.server.netty.HttpServerHandler.buildWebContext(HttpServerHandler.java:95)
	at com.blade.server.netty.HttpServerHandler.lambda$channelRead0$0(HttpServerHandler.java:84)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: 文件名过长
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createTempFile(File.java:2024)
	at java.io.File.createTempFile(File.java:2070)
	at io.netty.handler.codec.http.multipart.AbstractDiskHttpData.tempFile(AbstractDiskHttpData.java:90)
	at io.netty.handler.codec.http.multipart.AbstractDiskHttpData.addContent(AbstractDiskHttpData.java:163)
	at io.netty.handler.codec.http.multipart.DiskAttribute.addContent(DiskAttribute.java:99)
	at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.setFinalBuffer(HttpPostStandardRequestDecoder.java:614)
	at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.parseBodyAttributes(HttpPostStandardRequestDecoder.java:585)
	... 15 more

```

**Comment by pl1612127** [comment]
经过测试 ，应该是文章字数受限 ，具体不清楚限制多少 ，这个还不是数据库异常

**Comment by pl1612127** [comment]
发布下面内容都能失败
`
## 命名规范
-  避免单个字符名，让你的变量名有描述意义。
-  当命名对象、函数和实例时使用驼峰命名规则

```javascript
function thisIsMyFunction() {};
var user = new User({
  name: 'Bob Parr'
});
```
`

**Comment by pl1612127** [comment]
netty貌似有post过长的问题 ，blade没找到相关资料 ，等大佬处理了

**Comment by Lcarusd** [comment]
我也遇到这个问题...

**Comment by biezhi** [comment]
> 发布下面内容都能失败
> `
> 
> ## 命名规范
> * 避免单个字符名，让你的变量名有描述意义。
> * 当命名对象、函数和实例时使用驼峰命名规则
> 
> ```js
> function thisIsMyFunction() {};
> var user = new User({
>   name: 'Bob Parr'
> });
> ```
> 
> `

![image](https://user-images.githubusercontent.com/3849072/50479511-ef7a4400-0a11-11e9-9057-1ff92b3da8d6.png)

![image](https://user-images.githubusercontent.com/3849072/50479524-f86b1580-0a11-11e9-92a3-a23610ba2340.png)

**Comment by krscuti** [comment]
> > 发布下面内容都能失败
> > `
> > ## 命名规范
> > 
> > * 避免单个字符名，让你的变量名有描述意义。
> > * 当命名对象、函数和实例时使用驼峰命名规则
> > 
> > ```js
> > function thisIsMyFunction() {};
> > var user = new User({
> >   name: 'Bob Parr'
> > });
> > ```
> > 
> > 
> > `
> 
> ![image](https://user-images.githubusercontent.com/3849072/50479511-ef7a4400-0a11-11e9-9057-1ff92b3da8d6.png)
> 
> ![image](https://user-images.githubusercontent.com/3849072/50479524-f86b1580-0a11-11e9-92a3-a23610ba2340.png)

mark

**Comment by guodayang** [comment]
我修复了
http://www.gzzysoft.cn/blog/article/9

**Comment by flycat0112** [comment]
似乎在两个编辑器之间切换，复制会出现很多问题。

**Comment by flycat0112** [comment]
为什么会限制代码块的格式啊

**Comment by plum528** [comment]
这个问题的原因在另一个issue里面讲了
https://github.com/otale/tale/issues/578
可以参考里面的解决方法，不过我采用对content内容进行url编码，后端解码的方式处理的
