### ISSUE TITLE
win10下开发报找不到路径的错误

### ISSUE THREAD

**Issue by Cesar456** [otale/tale#51]
### 系统环境
win10

### IDE
IDEA 2016.3.4

### 错误详情
```java
log4j:WARN No appenders could be found for logger (com.blade.kit.base.Config).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
java.lang.NullPointerException
	at java.util.Properties$LineReader.readLine(Properties.java:434)
	at java.util.Properties.load0(Properties.java:353)
	at java.util.Properties.load(Properties.java:341)
	at com.tale.init.TaleJdbc.<clinit>(TaleJdbc.java:54)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.blade.kit.resource.AbstractClassReader.findClassByPackage(AbstractClassReader.java:88)
	at com.blade.kit.resource.AbstractClassReader.getClassByAnnotation(AbstractClassReader.java:156)
	at com.blade.kit.resource.AbstractClassReader.getClass(AbstractClassReader.java:46)
	at com.blade.ioc.IocApplication.lambda$initBeans$1(IocApplication.java:82)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.blade.ioc.IocApplication.initBeans(IocApplication.java:81)
	at com.blade.mvc.context.BladeInitListener.contextInitialized(BladeInitListener.java:81)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:865)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:532)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:828)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:344)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1480)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1442)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:788)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:540)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.server.Server.start(Server.java:452)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:419)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.blade.embedd.EmbedJettyServer.startup(EmbedJettyServer.java:157)
	at com.blade.embedd.EmbedJettyServer.startup(EmbedJettyServer.java:72)
	at com.blade.Blade.startNoJoin(Blade.java:498)
	at com.blade.Blade.start(Blade.java:471)
	at com.blade.Blade.start(Blade.java:477)
	at com.tale.Application.main(Application.java:8)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

```

### 错误详情图片
![qq 20170228101748](https://cloud.githubusercontent.com/assets/13900288/23388831/825a8ba8-fd9f-11e6-985c-987f1dac779d.png)

### 初步判断
在编译的时候没有把配置文件编译进去，导致
```
Properties props = new Properties();
        try {
            props.load(in);
```
在载入配置文件时报nullpointer的错误

**Comment by it-noob** [comment]
@Cesar456 添加resource配置，或者去看文档中的video
