### ISSUE TITLE
新的依赖好像有些问题

### ISSUE THREAD

**Issue by dongm2ez** [otale/tale#521]
```
2019/01/09 18:42:46  INFO [          _(:3」∠)_ ]             c.b.s.n.NettyServer : » Use NioEventLoopGroup
2019/01/09 18:42:51 ERROR [          _(:3」∠)_ ]                       c.b.Blade : Bind address error
 java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:130)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:558)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1358)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:1019)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:254)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:366)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at java.lang.Thread.run(Thread.java:748)

Disconnected from the target VM, address: '127.0.0.1:50258', transport: 'socket'
```

OS: macOS Mojave 10.14.2
JDK Version: jdk1.8.0_191

**Comment by zaoangod** [comment]
你的地址已经被使用了

**Comment by dongm2ez** [comment]
是的，我了解这个错误，但是这个端口每次都谁随机，而随机的那个端口上并没有启动什么程序

**Comment by zaoangod** [comment]
建议看看文档
http://lets-blade.com/docs/configuration.html

**Comment by dongm2ez** [comment]
我犯了个错误，我使用brew 更新了php ，php-fpm 会默认启动在9000端口上，而且使用的 root 权限，我使用不加sudo的命令`lsof -i:9000` 未查找到9000端口下运行的程序，以为是这个程序出现了问题，这真是个令人沮丧的错误
