### ISSUE TITLE
java.io.IOException: File name too long

### ISSUE THREAD

**Issue by yxiumei** [otale/tale#522]
报错信息:
```java
aDecoderException: java.io.IOException: File name too long
        at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.parseBodyAttributes(HttpPostStandardRequestDecoder.java:605)
        at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.parseBody(HttpPostStandardRequestDecoder.java:360)
        at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.offer(HttpPostStandardRequestDecoder.java:289)
        at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.offer(HttpPostStandardRequestDecoder.java:46)
        at io.netty.handler.codec.http.multipart.HttpPostRequestDecoder.offer(HttpPostRequestDecoder.java:227)
        at com.blade.mvc.http.HttpRequest.init(HttpRequest.java:359)
```
发布下面内容都是失败的

使用java提供的对象时，什么时候写泛型？
集合框架中常见，只要见到就要定义泛型用来接受类型使用集合时，将集合中存储的数据类型作为参数传到中即可
联系中问题:

```java
public class Test｛
  public void update(){
      List<String> list = new ArrayList<>();
  }
｝
```
2.泛型类一定是之前确定所有方法完全都是操作该类型,否则用泛型方法更合适.
所有方法完全都是操作该类型

如果把"= new ArrayList<>();"删掉其他内容不则可以发布成功。。。等待大佬处理

**Comment by jiahuixyz** [comment]
我把版本换成2.0.4后好使了

**Comment by Dabxiaofei** [comment]
io.netty.handler.codec.http.multipart.HttpPostRequestDecoder$ErrorDataDecoderException: java.io.IOException: File name too long
兄弟你怎么解决的啊，我这边大部分代码都不能上传。

**Comment by arjenzhou** [comment]
> 报错信息:
> 
> ```java
> aDecoderException: java.io.IOException: File name too long
>         at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.parseBodyAttributes(HttpPostStandardRequestDecoder.java:605)
>         at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.parseBody(HttpPostStandardRequestDecoder.java:360)
>         at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.offer(HttpPostStandardRequestDecoder.java:289)
>         at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.offer(HttpPostStandardRequestDecoder.java:46)
>         at io.netty.handler.codec.http.multipart.HttpPostRequestDecoder.offer(HttpPostRequestDecoder.java:227)
>         at com.blade.mvc.http.HttpRequest.init(HttpRequest.java:359)
> ```
> 
> 发布下面内容都是失败的
> 
> 使用java提供的对象时，什么时候写泛型？
> 集合框架中常见，只要见到就要定义泛型用来接受类型使用集合时，将集合中存储的数据类型作为参数传到中即可
> 联系中问题:
> 
> ```java
> public class Test｛
>   public void update(){
>       List<String> list = new ArrayList<>();
>   }
> ｝
> ```
> 
> 2.泛型类一定是之前确定所有方法完全都是操作该类型,否则用泛型方法更合适.
> 所有方法完全都是操作该类型
> 
> 如果把"= new ArrayList<>();"删掉其他内容不则可以发布成功。。。等待大佬处理

应该是`=`的问题，文章中带有`=`不能发布

**Comment by flycat0112** [comment]
同上
