### ISSUE TITLE
修改模板报错

### ISSUE THREAD

**Issue by i-misty** [otale/tale#526]
错误代码
[root@izwz993bv9azta8nrfwuhqz tale]# ./tool log
Caused by: java.io.IOException: Unable to create temporary file, /tmp/Attr_8223701987061108787_{"fileName":"partial/footer.html","content":"<footer id.att
	at java.io.File$TempDirectory.generateFile(File.java:1921)
	at java.io.File.createTempFile(File.java:2010)
	at java.io.File.createTempFile(File.java:2070)
	at io.netty.handler.codec.http.multipart.AbstractDiskHttpData.tempFile(AbstractDiskHttpData.java:90)
	at io.netty.handler.codec.http.multipart.AbstractDiskHttpData.addContent(AbstractDiskHttpData.java:163)
	at io.netty.handler.codec.http.multipart.DiskAttribute.addContent(DiskAttribute.java:99)
	at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.parseBodyAttributes(HttpPostStandardRequestDecoder.java:593)
	... 15 more

^C
[root@izwz993bv9azta8nrfwuhqz tale]# vim logs/
[root@izwz993bv9azta8nrfwuhqz tale]# vim logs/
[root@izwz993bv9azta8nrfwuhqz tale]# ./tool log
Caused by: java.io.IOException: Unable to create temporary file, /tmp/Attr_8223701987061108787_{"fileName":"partial/footer.html","content":"<footer id.att
	at java.io.File$TempDirectory.generateFile(File.java:1921)
	at java.io.File.createTempFile(File.java:2010)
	at java.io.File.createTempFile(File.java:2070)
	at io.netty.handler.codec.http.multipart.AbstractDiskHttpData.tempFile(AbstractDiskHttpData.java:90)
	at io.netty.handler.codec.http.multipart.AbstractDiskHttpData.addContent(AbstractDiskHttpData.java:163)
	at io.netty.handler.codec.http.multipart.DiskAttribute.addContent(DiskAttribute.java:99)
	at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.parseBodyAttributes(HttpPostStandardRequestDecoder.java:593)
	... 15 more

**Comment by Linindoo** [comment]
不能创建临时文件？那在服务器上是否有写的权限呢？

**Comment by zaoangod** [comment]
> 错误代码
> [root@izwz993bv9azta8nrfwuhqz tale]# ./tool log
> Caused by: java.io.IOException: Unable to create temporary file, /tmp/Attr_8223701987061108787_{"fileName":"partial/footer.html","content":"<footer id.att
> at java.io.File$TempDirectory.generateFile(File.java:1921)
> at java.io.File.createTempFile(File.java:2010)
> at java.io.File.createTempFile(File.java:2070)
> at io.netty.handler.codec.http.multipart.AbstractDiskHttpData.tempFile(AbstractDiskHttpData.java:90)
> at io.netty.handler.codec.http.multipart.AbstractDiskHttpData.addContent(AbstractDiskHttpData.java:163)
> at io.netty.handler.codec.http.multipart.DiskAttribute.addContent(DiskAttribute.java:99)
> at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.parseBodyAttributes(HttpPostStandardRequestDecoder.java:593)
> ... 15 more
> 
> ^C
> [root@izwz993bv9azta8nrfwuhqz tale]# vim logs/
> [root@izwz993bv9azta8nrfwuhqz tale]# vim logs/
> [root@izwz993bv9azta8nrfwuhqz tale]# ./tool log
> Caused by: java.io.IOException: Unable to create temporary file, /tmp/Attr_8223701987061108787_{"fileName":"partial/footer.html","content":"<footer id.att
> at java.io.File$TempDirectory.generateFile(File.java:1921)
> at java.io.File.createTempFile(File.java:2010)
> at java.io.File.createTempFile(File.java:2070)
> at io.netty.handler.codec.http.multipart.AbstractDiskHttpData.tempFile(AbstractDiskHttpData.java:90)
> at io.netty.handler.codec.http.multipart.AbstractDiskHttpData.addContent(AbstractDiskHttpData.java:163)
> at io.netty.handler.codec.http.multipart.DiskAttribute.addContent(DiskAttribute.java:99)
> at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.parseBodyAttributes(HttpPostStandardRequestDecoder.java:593)
> ... 15 more

我也出现这个问题了, 好像编辑内容的时候, 里面的特殊字符, 提交保存的时候, 后台会报错
