### ISSUE TITLE
启动项目，进入网站安装页，无法进行下一步操作

### ISSUE THREAD

**Issue by eizmoo** [otale/tale#528]
页面报错，没有jq
> jQuery is not defined

**Comment by pixeltrek** [comment]
![default](https://user-images.githubusercontent.com/40168641/51546557-5b2fbf80-1e9f-11e9-9912-7fbb9d3ca64a.png)

**Comment by NoaAlan** [comment]
我也碰到这个问题，清除缓存后可以了

**Comment by yiran-culture** [comment]
我也遇到了，清除缓存不行啊，你们是怎么解决的？

**Comment by shaokunV1** [comment]
希望有大佬解决后提醒小弟一下

**Comment by NoaAlan** [comment]
> 我也遇到了，清除缓存不行啊，你们是怎么解决的？

试试用无痕浏览打开，有的CDN加载可能有问题

**Comment by zoujiayu** [comment]
删除tale.db和install.lock
重启tale，ctrl+f5清空缓存，即可

**Comment by zoujiayu** [comment]
Error Logs

2019/02/12 18:30:49  INFO [   worker@thread-4 ]               c.t.h.BaseWebHook : IP: 27.0.0.1, UserAgent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
2019/02/12 18:30:49  INFO [   worker@thread-4 ]       c.b.s.n.HttpServerHandler :  200   603ms  GET    /
2019/02/12 18:30:49  INFO [   worker@thread-4 ]               c.t.h.BaseWebHook : IP: 27.0.0.1, UserAgent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
2019/02/12 18:30:49  INFO [   worker@thread-4 ]       c.b.s.n.HttpServerHandler :  200   534ms  GET    /install
2019/02/12 18:30:49  INFO [   worker@thread-4 ]             j.t.JetTemplateImpl : Loading template: install.html
2019/02/12 18:31:13  INFO [   worker@thread-3 ]               c.t.h.BaseWebHook : IP: 27.0.0.1, UserAgent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
2019/02/12 18:31:13 DEBUG [   worker@thread-3 ]                       o.s.Query : Execute SQL => INSERT INTO t_users(username, password, screen_name, created) VALUES (?, ?, ?, ?)
2019/02/12 18:31:13 DEBUG [   worker@thread-3 ]                       o.s.Query : Parameters  => [test, 912b7bc95fb9e6885a4685746433f39a, test, 1549967473]
2019/02/12 18:31:13  WARN [   worker@thread-3 ]                  o.s.Connection : Could not roll back transaction. message: {} java.sql.SQLException: database in auto-commit mode
	at org.sqlite.jdbc3.JDBC3Connection.rollback(JDBC3Connection.java:184)
	at org.sql2o.Connection.rollback(Connection.java:130)
	at org.sql2o.Connection.onException(Connection.java:74)
	at org.sql2o.Query.executeUpdate(Query.java:398)
	at io.github.biezhi.anima.core.AnimaQuery.save(AnimaQuery.java:1212)
	at io.github.biezhi.anima.Model.save(Model.java:28)
	at com.tale.service.SiteService.initSite(SiteService.java:53)
	at com.tale.controller.InstallController.doInstall(InstallController.java:62)
	at com.tale.controller.InstallControllerMethodAccess.invoke(Unknown Source)
	at com.blade.reflectasm.MethodAccess.invoke(MethodAccess.java:43)
	at com.blade.server.netty.RouteMethodHandler.routeHandle(RouteMethodHandler.java:256)
	at com.blade.server.netty.RouteMethodHandler.handle(RouteMethodHandler.java:87)
	at com.blade.server.netty.HttpServerHandler.executeLogic(HttpServerHandler.java:158)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at java.lang.Thread.run(Thread.java:748)

2019/02/12 18:31:13 ERROR [   worker@thread-3 ]       c.b.s.n.HttpServerHandler :  500          POST /install
2019/02/12 18:31:13 ERROR [   worker@thread-3 ] c.b.m.h.DefaultExceptionHandler :  org.sql2o.Sql2oException: Error in executeUpdate, [SQLITE_CONSTRAINT_UNIQUE]  A UNIQUE constraint failed (UNIQUE constraint failed: t_users.username)
	at org.sql2o.Query.executeUpdate(Query.java:399)
	at io.github.biezhi.anima.core.AnimaQuery.save(AnimaQuery.java:1212)
	at io.github.biezhi.anima.Model.save(Model.java:28)
	at com.tale.service.SiteService.initSite(SiteService.java:53)
	at com.tale.controller.InstallController.doInstall(InstallController.java:62)
	at com.tale.controller.InstallControllerMethodAccess.invoke(Unknown Source)
	at com.blade.reflectasm.MethodAccess.invoke(MethodAccess.java:43)
	at com.blade.server.netty.RouteMethodHandler.routeHandle(RouteMethodHandler.java:256)
	at com.blade.server.netty.RouteMethodHandler.handle(RouteMethodHandler.java:87)
	at com.blade.server.netty.HttpServerHandler.executeLogic(HttpServerHandler.java:158)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_UNIQUE]  A UNIQUE constraint failed (UNIQUE constraint failed: t_users.username)
	at org.sqlite.core.DB.newSQLException(DB.java:909)
	at org.sqlite.core.DB.newSQLException(DB.java:921)
	at org.sqlite.core.DB.execute(DB.java:825)
	at org.sqlite.core.DB.executeUpdate(DB.java:863)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:99)
	at org.sql2o.Query.executeUpdate(Query.java:394)
	... 17 more

2019/02/12 18:31:13  INFO [   worker@thread-3 ]             j.t.JetTemplateImpl : Loading template: /comm/error_500.html

**Comment by zoujiayu** [comment]
Error Logs
~~~
2019/02/12 18:30:49  INFO [   worker@thread-4 ]               c.t.h.BaseWebHook : IP: 27.0.0.1, UserAgent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
2019/02/12 18:30:49  INFO [   worker@thread-4 ]       c.b.s.n.HttpServerHandler :  200   603ms  GET    /
2019/02/12 18:30:49  INFO [   worker@thread-4 ]               c.t.h.BaseWebHook : IP: 27.0.0.1, UserAgent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
2019/02/12 18:30:49  INFO [   worker@thread-4 ]       c.b.s.n.HttpServerHandler :  200   534ms  GET    /install
2019/02/12 18:30:49  INFO [   worker@thread-4 ]             j.t.JetTemplateImpl : Loading template: install.html
2019/02/12 18:31:13  INFO [   worker@thread-3 ]               c.t.h.BaseWebHook : IP: 27.0.0.1, UserAgent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
2019/02/12 18:31:13 DEBUG [   worker@thread-3 ]                       o.s.Query : Execute SQL => INSERT INTO t_users(username, password, screen_name, created) VALUES (?, ?, ?, ?)
2019/02/12 18:31:13 DEBUG [   worker@thread-3 ]                       o.s.Query : Parameters  => [test, 912b7bc95fb9e6885a4685746433f39a, test, 1549967473]
2019/02/12 18:31:13  WARN [   worker@thread-3 ]                  o.s.Connection : Could not roll back transaction. message: {} java.sql.SQLException: database in auto-commit mode
	at org.sqlite.jdbc3.JDBC3Connection.rollback(JDBC3Connection.java:184)
	at org.sql2o.Connection.rollback(Connection.java:130)
	at org.sql2o.Connection.onException(Connection.java:74)
	at org.sql2o.Query.executeUpdate(Query.java:398)
	at io.github.biezhi.anima.core.AnimaQuery.save(AnimaQuery.java:1212)
	at io.github.biezhi.anima.Model.save(Model.java:28)
	at com.tale.service.SiteService.initSite(SiteService.java:53)
	at com.tale.controller.InstallController.doInstall(InstallController.java:62)
	at com.tale.controller.InstallControllerMethodAccess.invoke(Unknown Source)
	at com.blade.reflectasm.MethodAccess.invoke(MethodAccess.java:43)
	at com.blade.server.netty.RouteMethodHandler.routeHandle(RouteMethodHandler.java:256)
	at com.blade.server.netty.RouteMethodHandler.handle(RouteMethodHandler.java:87)
	at com.blade.server.netty.HttpServerHandler.executeLogic(HttpServerHandler.java:158)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at java.lang.Thread.run(Thread.java:748)

2019/02/12 18:31:13 ERROR [   worker@thread-3 ]       c.b.s.n.HttpServerHandler :  500          POST /install
2019/02/12 18:31:13 ERROR [   worker@thread-3 ] c.b.m.h.DefaultExceptionHandler :  org.sql2o.Sql2oException: Error in executeUpdate, [SQLITE_CONSTRAINT_UNIQUE]  A UNIQUE constraint failed (UNIQUE constraint failed: t_users.username)
	at org.sql2o.Query.executeUpdate(Query.java:399)
	at io.github.biezhi.anima.core.AnimaQuery.save(AnimaQuery.java:1212)
	at io.github.biezhi.anima.Model.save(Model.java:28)
	at com.tale.service.SiteService.initSite(SiteService.java:53)
	at com.tale.controller.InstallController.doInstall(InstallController.java:62)
	at com.tale.controller.InstallControllerMethodAccess.invoke(Unknown Source)
	at com.blade.reflectasm.MethodAccess.invoke(MethodAccess.java:43)
	at com.blade.server.netty.RouteMethodHandler.routeHandle(RouteMethodHandler.java:256)
	at com.blade.server.netty.RouteMethodHandler.handle(RouteMethodHandler.java:87)
	at com.blade.server.netty.HttpServerHandler.executeLogic(HttpServerHandler.java:158)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_UNIQUE]  A UNIQUE constraint failed (UNIQUE constraint failed: t_users.username)
	at org.sqlite.core.DB.newSQLException(DB.java:909)
	at org.sqlite.core.DB.newSQLException(DB.java:921)
	at org.sqlite.core.DB.execute(DB.java:825)
	at org.sqlite.core.DB.executeUpdate(DB.java:863)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:99)
	at org.sql2o.Query.executeUpdate(Query.java:394)
	... 17 more

2019/02/12 18:31:13  INFO [   worker@thread-3 ]             j.t.JetTemplateImpl : Loading template: /comm/error_500.html
~~~
@biezhi

**Comment by shaokunV1** [comment]
将整体项目编码设为utf-8就好了，上次有个项目编码是gbk忘了改回来。(我怎么会犯这种错误 :(   )

**Comment by haohaolio** [comment]
同遇到问题,强制刷新即可
