### ISSUE TITLE
添加了code不能发表文章。以前没有这个错误，这次升级后就有了

### ISSUE THREAD

**Issue by flycat0112** [otale/tale#546]
@biezhi @Jackeylou @VilenEera @XGFan 你好：
feedback如下
图片：

![](https://www.1314i58.com/upload/2019/03/ppu2h12no2gbtopdv997fk45g2.png)

后台日志错误信息：
```
2019/03/22 19:22:52 ERROR [   worker@thread-1 ] c.b.m.h.DefaultExceptionHandler :  io.netty.handler.codec.http.multipart.HttpPostReque     stDecoder$ErrorDataDecoderException: java.io.IOException: Unable to create temporary file, /tmp/Attr_1256944523157625391_{"cid":36,"ti     tle":"Connection manager(IM)配置文件详细说明","slug":"openfire-cm-config","created":1553251920,"modified":1553252138,"content":"# 一、
     connection manager的作用\n---\n![alt](https:/www.1314i58.com/upload/2019/03/tdt1ps5j3ug2vp33v8jrau225o.gif)\nconnection Manager 简称CM     的创作初始是为了提高openfire的用户并发数。\n\n比如：\n\n每个连接管理器应该至少处理五千个并发用户，如果openfire允许只能同时连接 300个连
     接，那么最终集群理论上的并发就是150万个，但是这是理想的情况下， 因为一个CM有时候为了提高并发会同时占用多条连接。\n\nOpenfire首先要配置
     5262端口开启：\n![alt](https:/www.1314i58.com/upload/2019/03/tioi9le6d4gbsqjc9bjkc9hke5.png)\n# 二、connection manager的配置文件\nCM中
     部分属性的作用\n```xml\n\n<?xml version.att
2620         at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.parseBodyAttributes(HttpPostStandardRequestDecoder.jav     a:605)
2621         at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.parseBody(HttpPostStandardRequestDecoder.java:360)
2622         at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.offer(HttpPostStandardRequestDecoder.java:289)
2623         at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.offer(HttpPostStandardRequestDecoder.java:46)
2624         at io.netty.handler.codec.http.multipart.HttpPostRequestDecoder.offer(HttpPostRequestDecoder.java:227)
2625         at com.blade.mvc.http.HttpRequest.init(HttpRequest.java:359)

```
环境：
系统：elementary（ubuntu）
浏览器：firefox（65.0.1 (64-bit)）

附：window 系统里面也测试了，并且后台有报错，不是前端的问题。

**Comment by eternalstone** [comment]
我也有这个问题

**Comment by flycat0112** [comment]
基本上更新 过的都不能用了。

**Comment by flycat0112** [comment]
似乎博主不维护这个了

**Comment by liangtingchen** [comment]
这个回答可以解决https://github.com/otale/tale/issues/578#issuecomment-567367832
