### ISSUE TITLE
启动的时候成功，访问报错

### ISSUE THREAD

**Issue by domiye** [otale/tale#564]
2019/07/04 11:56:57 ERROR [  worker@thread-10 ]      c.b.s.n.RouteMethodHandler : Render view error com.blade.exception.TemplateException: java.lang.ClassCastException: [B cannot be cast to [C
        at com.blade.mvc.view.template.JetbrickTemplateEngine.render(JetbrickTemplateEngine.java:105)
        at com.blade.server.netty.RouteMethodHandler$1.onView(RouteMethodHandler.java:122)
        at com.blade.mvc.http.ViewBody.write(ViewBody.java:26)
        at com.blade.server.netty.RouteMethodHandler.handleResponse(RouteMethodHandler.java:106)
        at com.blade.server.netty.HttpServerHandler.buildResponse(HttpServerHandler.java:128)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.ClassCastException: [B cannot be cast to [C
        at jetbrick.template.parser.ast.AstText$Jdk6CharArrayEncoder.<init>(AstText.java:281)
        at jetbrick.template.parser.ast.AstText.execute(AstText.java:217)
        at jetbrick.template.parser.ast.AstStatementList.execute(AstStatementList.java:212)
        at jetbrick.template.parser.ast.AstTemplate.execute(AstTemplate.java:37)
        at jetbrick.template.JetTemplateImpl.doInterpret(JetTemplateImpl.java:160)
        at jetbrick.template.JetTemplateImpl.render(JetTemplateImpl.java:141)
        at com.blade.mvc.view.template.JetbrickTemplateEngine.render(JetbrickTemplateEngine.java:103)
        ... 11 more

2019/07/04 11:56:57 ERROR [  worker@thread-10 ]       c.b.s.n.HttpServerHandler :  500          GET /install

**Comment by yoletPig** [comment]
我也是这样，为什么呢？

**Comment by tamato2050** [comment]
這個問題解決了嗎？
