### ISSUE TITLE
启动装载模板时出错

### ISSUE THREAD

**Issue by yzchengrui** [otale/tale#576]
错误信息如下：
2019/11/13 09:09:15  INFO [   worker@thread-1 ]             j.t.JetTemplateImpl : Loading template: install.html
2019/11/13 09:09:22 ERROR [   worker@thread-1 ]      c.b.s.n.RouteMethodHandler : Render view error com.blade.exception.TemplateException: java.lang.ClassCastException: class [B cannot be cast to class [C ([B and [C are in module java.base of loader 'bootstrap')
	at com.blade.mvc.view.template.JetbrickTemplateEngine.render(JetbrickTemplateEngine.java:105)
	at com.blade.server.netty.RouteMethodHandler$1.onView(RouteMethodHandler.java:122)
	at com.blade.mvc.http.ViewBody.write(ViewBody.java:26)
	at com.blade.server.netty.RouteMethodHandler.handleResponse(RouteMethodHandler.java:106)
	at com.blade.server.netty.HttpServerHandler.buildResponse(HttpServerHandler.java:128)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassCastException: class [B cannot be cast to class [C ([B and [C are in module java.base of loader 'bootstrap')
	at jetbrick.template.parser.ast.AstText$Jdk6CharArrayEncoder.<init>(AstText.java:276)
	at jetbrick.template.parser.ast.AstText.execute(AstText.java:214)
	at jetbrick.template.parser.ast.AstStatementList.execute(AstStatementList.java:212)
	at jetbrick.template.parser.ast.AstTemplate.execute(AstTemplate.java:37)
	at jetbrick.template.JetTemplateImpl.doInterpret(JetTemplateImpl.java:160)
	at jetbrick.template.JetTemplateImpl.render(JetTemplateImpl.java:141)
	at com.blade.mvc.view.template.JetbrickTemplateEngine.render(JetbrickTemplateEngine.java:103)
	... 12 more

**Comment by chaw1** [comment]
我出现这个问题是我的ubuntu装了jdk11，切成jdk8就好了~

**Comment by yzchengrui** [comment]
谢谢
