### ISSUE TITLE
编辑模板出错了，临时文件没法创建？怎么感觉是命名太长的原因导致的问题

### ISSUE THREAD

**Issue by Ccapton** [otale/tale#585]
Caused by: java.io.IOException: Unable to create temporary file, **/tmp/Attr_6793862782715443818_{"fileName":"partial/sidebar.html","content":"<aside id.att**
at java.io.File$TempDirectory.generateFile(File.java:1921)
at java.io.File.createTempFile(File.java:2010)
at java.io.File.createTempFile(File.java:2070)

**Comment by Ccapton** [comment]
### 在idea开发模式运行下证实，确实是文件命名过长的问题

**Comment by usgate** [comment]
> ### 在idea开发模式运行下证实，确实是文件命名过长的问题

因为解析器解析= 这个符号异常导致的
