### ISSUE TITLE
启动成功之后加载不进去

### ISSUE THREAD

**Issue by chuxingran** [otale/tale#594]
![image](https://user-images.githubusercontent.com/52754257/111306246-f1805a00-8692-11eb-92cc-28b53a145315.png)
启动成功之后加载不进去，在Ubuntu服务器里面也是一样
![image](https://user-images.githubusercontent.com/52754257/111306325-0c52ce80-8693-11eb-9e87-5c34aba3bd35.png)

**Comment by zoujiayu** [comment]
~~~ tale.log
2021/03/31 19:52:48 ERROR [   worker@thread-2 ]      c.b.s.n.RouteMethodHandler : Render view error com.blade.exception.TemplateException: java.lang.ClassCastException: class [B cannot be cast to class [C ([B and [C are in module java.base of loader 'bootstrap')
	at com.blade.mvc.view.template.JetbrickTemplateEngine.render(JetbrickTemplateEngine.java:105)
	at com.blade.server.netty.RouteMethodHandler$1.onView(RouteMethodHandler.java:122)
	at com.blade.mvc.http.ViewBody.write(ViewBody.java:26)
	at com.blade.server.netty.RouteMethodHandler.handleResponse(RouteMethodHandler.java:106)
	at com.blade.server.netty.HttpServerHandler.buildResponse(HttpServerHandler.java:128)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassCastException: class [B cannot be cast to class [C ([B and [C are in module java.base of loader 'bootstrap')
	at jetbrick.template.parser.ast.AstText$Jdk6CharArrayEncoder.<init>(AstText.java:281)
	at jetbrick.template.parser.ast.AstText.execute(AstText.java:217)
	at jetbrick.template.parser.ast.AstStatementList.execute(AstStatementList.java:212)
	at jetbrick.template.parser.ast.AstTemplate.execute(AstTemplate.java:37)
	at jetbrick.template.JetTemplateImpl.doInterpret(JetTemplateImpl.java:160)
	at jetbrick.template.JetTemplateImpl.render(JetTemplateImpl.java:141)
	at com.blade.mvc.view.template.JetbrickTemplateEngine.render(JetbrickTemplateEngine.java:103)
	... 11 more
~~~
使用Firefox首次访问Tale时复现该问题，Releases Tale-V2.5

./tool restart后使用Chrome(V89)访问正常，Firefox(V87)偶尔出现Js加载问题(强刷多次后正常)
![3nUg8hXHzPaFCl9](https://user-images.githubusercontent.com/20484791/113144363-bb7cd180-925f-11eb-854e-369c9b6fe550.png)
