### ISSUE TITLE
从git clone的源码mvn install 之后的target目录下的tale.jar无法直接运行呢？

### ISSUE THREAD

**Issue by judeys** [otale/tale#73]
如题

**Comment by biezhi** [comment]
本地打包命令：
```bash
mvn clean package assembly:single -Pprod -Dmaven.test.skip=true
```

**Comment by Cesar456** [comment]
使用mvn clean package assembly:single -Pprod -Dmaven.test.skip=true打包后还是无法运行，提示：
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/blade/Blade
        at com.tale.Application.main(Application.java:8)
Caused by: java.lang.ClassNotFoundException: com.blade.Blade
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 1 more
```

**Comment by biezhi** [comment]
@Cesar456 你先使用 `mvn clean compile` 编译一下，这时候会下载依赖并编译代码，看这个提示应该是没有下载到jar包。

**Comment by Cesar456** [comment]
是的，我先用了```mvn clean compile``` 然后再```mvn clean package assembly:single -Pprod -Dmaven.test.skip=true```，然后报出了这个错误。
