### ISSUE TITLE
BindException: Address already in use: bind

### ISSUE THREAD

**Issue by SchuckBeta** [otale/tale#77]
错误：
[tale] 2017-03-02 15:42:18,434 INFO  [main] org.eclipse.jetty.server.handler.ContextHandler | Started o.e.j.w.WebAppContext@6ca0256d{/,file:///E:/workspace-sts/tale/target/classes/,AVAILABLE}
Exception in thread "main" com.blade.exception.EmbedServerException: java.net.BindException: Address already in use: bind
	at com.blade.embedd.EmbedJettyServer.startup(EmbedJettyServer.java:161)
	at com.blade.embedd.EmbedJettyServer.startup(EmbedJettyServer.java:72)
	at com.blade.Blade.startNoJoin(Blade.java:498)
	at com.blade.Blade.start(Blade.java:471)
	at com.blade.Blade.start(Blade.java:477)
	at com.tale.Application.main(Application.java:15)
Caused by: java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Unknown Source)
	at sun.nio.ch.Net.bind(Unknown Source)
	at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
	at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:298)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:431)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.blade.embedd.EmbedJettyServer.startup(EmbedJettyServer.java:157)
	... 5 more

异常定位：
public class Application {

    public static void main(String[] args) throws Exception {
        TaleLoader.init();
        TaleLoader.loadPlugin(new File("/Users/biezhi/workspace/projects/java/plugin_upyun/target/plguin_upyun.jar"));
        $().start(Application.class);
    }

}

new File("/Users/biezhi/workspace/projects/java/plugin_upyun/target/plguin_upyun.jar")
这一句加载的jar没有，请问是干嘛用的，导致这一段代码没有执行
 public static void loadPlugin(File pluginFile) {
        try {
            if(pluginFile.isFile() && pluginFile.getName().endsWith(".jar")){
                URLClassLoader classLoader = (URLClassLoader) ClassLoader.getSystemClassLoader();
                Method add = URLClassLoader.class.getDeclaredMethod("addURL", new Class[]{URL.class});
                add.setAccessible(true);
                add.invoke(classLoader, pluginFile.toURI().toURL());
            }
        } catch (Exception e) {
            throw new RuntimeException("插件 [" + pluginFile.getName() + "] 加载失败");
        }
    }

**Comment by trytrytryiii** [comment]
之前启动的服务是不是没有关闭
那个像是又拍云插件，没什么影响

**Comment by SchuckBeta** [comment]
已经解决了，插件是另外一个项目，已经下载下来打包了，  端口占用把推荐的#server.port=9001
改为其它的就可以了server.port=9111，
但是打包插件到本地。改完main里面的路径
 TaleLoader.loadPlugin(new File("C:/Users/DC/.m2/repository/com/tale/plugin/plguin_upyun/1.0.0/plguin_upyun.jar"));

`
System.out.println("--pluginFile-------------------------------------");
        	System.out.println(pluginFile.isFile());
        	System.out.println(pluginFile.getName());
        	System.out.println("--pluginFile-------------------------------------");
`
打印结果为false

**Comment by biezhi** [comment]
@SchuckBeta sorry，这是个问题，我马上修复
