### ISSUE TITLE
代码修改后，如何打包上传到服务器？

### ISSUE THREAD

**Issue by fastener** [otale/tale#84]
修改了部分java代码后，是打成runnable jar 然后上传服务器吗？
打包后 报Exception in thread "main" java.lang.NoClassDefFoundError: com/blade/Blade
	at com.tale.Application.main(Application.java:14)
Caused by: java.lang.ClassNotFoundException: com.blade.Blade
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
错误

**Comment by pkwenda** [comment]
```mvn clean package assembly:single -Pprod -Dmaven.test.skip=true```

**Comment by biezhi** [comment]
打包的命令是：`mvn clean package assembly:single -Pprod -Dmaven.test.skip=true`

打包后会在 `target/dist` 文件夹下产生一个目录
