### ISSUE TITLE
代码修改后，mvn编译后在服务器上运行错误

### ISSUE THREAD

**Issue by fastener** [otale/tale#86]
修改了部分java代码后，使用 mvn clean package assembly:single -Pprod -Dmaven.test.skip=true 打包后，在本地使用java -jar xxx/xxx.jar 运行正常。 然后把jar包部署到服务器，运行 直接报以错误：
Exception in thread "main" java.lang.NoClassDefFoundError: com/blade/Blade
at com.tale.Application.main(Application.java:14)
Caused by: java.lang.ClassNotFoundException: com.blade.Blade
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 1 more
请问怎么为什么？

**Comment by biezhi** [comment]
发布到服务器的时候把整个目录都传上去，不是一个jar哦
