### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by LaudOak** [otale/tale#94]
问题是这样的,运行起来以后在控制台添加了一个标签,控制台抛出异常页面就访问不了了.
再次启动就这样了:
`➜  tale java -jar tale-1.03.jar
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.tale.init.TaleLoader.loadPlugins(TaleLoader.java:47)
	at com.tale.init.TaleLoader.init(TaleLoader.java:26)
	at com.tale.Application.main(Application.java:10)
Caused by: java.lang.NullPointerException
	at com.tale.controller.admin.AttachController.<clinit>(AttachController.java:46)
	... 3 more
`

**Comment by biezhi** [comment]
这个问题我没有遇到，可以详细描述一下你的情况吗？
